### PR TITLE
MQTT connection builder custom authorizer support

### LINKED ISSUE #267: Default Custom Authorizer invalid TLS ALPN
### Describe the bug

The SDK is checking for `x-amz-customauthorizer-name` string inside the username to override the TLS ALPN list and use custom authorizers:
https://github.com/aws/aws-iot-device-sdk-java-v2/blob/c04ce42a7c83bb6aa5f8e51b2cd1af44f99fc7d1/sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java#L521-L524

When specifing a custom domain with a default custom authorizer (see [Creating and configuring custom domains](https://docs.aws.amazon.com/iot/latest/developerguide/iot-custom-endpoints-configurable-custom.html), `x-amz-customauthorizer-name` parameter is not required. If override is disabled, specifing the parameter may result in an error.

### Expected Behavior

I can connect to a custom domain using the default authrizer, without specifing `x-amz-customauthorizer-name` parameter.

### Current Behavior

Skipping `x-amz-customauthorizer-name` parameter does not set the correct TLS ALPN.

### Reproduction Steps

- Create a custom authorizer.
- Create a domain that uses the authorizer as default, without override.
- Attempt to connect to the custom domain without specifing the authorizer name.
- Connection fails with `software.amazon.awssdk.crt.mqtt.MqttException: TLS (SSL) negotiation failed`

Example code:
```kotlin
AwsIotMqttConnectionBuilder
    .newDefaultBuilder()
    .withCertificateAuthority(
        // AmazonRootCA1.pem
    )
    .withEndpoint("mqtt.example.com")
    .withPort(443)
    .withBootstrap(cb)
    .withClientId("hello-world")
    .withUsername(
        "username" +
                "?x-amz-customauthorizer-signature=......" +
                "&token=....."
    )
    .build()
```

### Possible Solution

I don't see a query parameter required in all situations for custom authorizer to use as an implicit flag.
Name is optional in default authorizers. Signature can be disabled.
Probably an explicit building method is required.

### Additional Information/Context

I've been working around this issue by appending `&workaround=x-amz-customauthorizer-name` query parameter to trigger the builder condition.

### SDK version used

1.8.4

### Environment details (OS name and version, etc.)

Fedora 34, Kotlin 1.6.20, Java 11

### PR DESCRIPTION
**Pull request by TwistedTwigleg**
*Issue #, if available:*

Closes #267

*Description of changes:*

Adds a custom authorizer builder to the MQTT connection builder so it is possible to create a custom authorizer connection without having to pass `x-amz-customauthorizer-name` or `x-amz-customauthorizer-signature`. Also improved the code for checking if `username` contains a custom authorizer so it detects custom signatures, and added a warning that prints if trying to connect to a custom authorizer but not on port 443.

____________

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.*

### CODE REVIEW

File: sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java [hunk 1]
```diff
@@ -500,6 +505,74 @@ public AwsIotMqttConnectionBuilder withWebsocketCredentialsProvider(CredentialsP
...
+        if (username == null) {
+            if (config.getUsername() != null) {
+                username_string += config.getUsername();
+            }
+        } else {
+            username_string += username;
+        }
+
+        if (authorizerName != null) {
+            if (username_added_query == false) {
```
Comment (bretambrose) [inline sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java:538]: This check is always true which makes me think that something is missing

File: sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java [hunk 2]
```diff
@@ -500,6 +505,74 @@ public AwsIotMqttConnectionBuilder withWebsocketCredentialsProvider(CredentialsP
...
+            }
+            if (authorizerName.contains("x-amz-customauthorizer-name=")) {
+                username_string += authorizerName;
+            } else {
+                username_string += "x-amz-customauthorizer-name=" + authorizerName;
+            }
+        }
+
+        if (signature != null) {
+            if (username_added_query == false) {
```
Comment (bretambrose) [inline sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java:552]: This if-else matches exactly a block above.  I bet there's a way to refactor into a helper function that would make that go away.

In fact the larger if-statement may be refactorable: 
```add_username_parameter(..., "x-amz-customauthorizer-name", authorizerName)```
&
```add_username_parameter(..., "x-amz-customauthorizer-signature", signature)```
etc...

**Comment by bretambrose** [comment]
Also, can you add a Lambda + any other necessary AWS infrastructure to the team account and then add a sample for custom auth?  It's a bit out of scope, so maybe do it as a follow up to this.

**Comment by TwistedTwigleg** [comment]
Awesome, thanks for the review! I'll adjust the code accordingly.
For the tests, I *think* it should be easy enough to add, though I might leave it for a follow-up for early next week 👍

**Comment by TwistedTwigleg** [comment]
Seems the test is having some sort of TLS issue. Running it locally does not have the same issue. Will dig into it and fix a fix soon.

File: sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java [hunk 3]
```diff
@@ -500,6 +505,74 @@ public AwsIotMqttConnectionBuilder withWebsocketCredentialsProvider(CredentialsP
...
+            }
+        } else {
+            username_string += username;
+        }
+
+        if (authorizerName != null) {
+            username_string = addUsernameParameter(username_string, authorizerName, "x-amz-customauthorizer-name=", username_added_query);
+            username_added_query = true;
+        }
+        if (signature != null) {
```
Comment (sbSteveK) [inline sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java:559]: Based on previous change, should this be checking if username_added_query is still false before proceeding since it may have been changed to true at this point?

File: sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java [hunk 4]
```diff
@@ -500,6 +505,74 @@ public AwsIotMqttConnectionBuilder withWebsocketCredentialsProvider(CredentialsP
...
+            username_string = addUsernameParameter(username_string, signature, "x-amz-customauthorizer-signature=", username_added_query);
+            username_added_query = true;
```
Comment (sbSteveK) [inline sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java:561]: username_added_query doesn't appear to be used beyond this point so we may be able to remove this true assignment.

File: codebuild/samples/linux-smoke-tests.yml [hunk 5]
```diff
@@ -15,6 +15,10 @@ phases:
       - $CODEBUILD_SRC_DIR/codebuild/samples/setup-linux.sh
       - $CODEBUILD_SRC_DIR/codebuild/samples/pubsub-linux.sh
       - $CODEBUILD_SRC_DIR/codebuild/samples/connect-linux.sh
+
+      # Currently dies in CI every time despite working perfectly fine locally - not sure why.
+      # TODO - fix/revisit this!
```
Comment (sbSteveK) [inline codebuild/samples/linux-smoke-tests.yml:20]: Unless this is a pressing matter and someone is waiting for it, maybe we should wait on this merge to main until we get it working in CI. Otherwise this might become a task that just kind of falls behind. That's my opinion anyway, maybe worth discussing at standup.

File: sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java (hunk 3 above)
Comment (TwistedTwigleg) [reply sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java:559]: No, though this confused me initially as well which is why the previous change checked for it. We need to add it if the username is added or not so we can support having a username and a signature.

_________

Slightly off-topic note:

With a custom authorizer, you are not required to pass a username. It is possible you might have only a signature as the first parameter. It is also possible to have only a username, a username and signature, or nothing at all! All of the arguments you pass to a custom authorizer are optional, which is kinda strange but it's mentioned in the documentation and works. I'm guessing it is for different configurations and so it also supports default custom authroizers, which may just be an endpoint. It is rather strange though from my (limited) current understanding.

__________

I should change the name of the variable though, as it's really just for determining which character to use when adding it to the username string.

File: codebuild/samples/linux-smoke-tests.yml (hunk 5 above)
Comment (TwistedTwigleg) [reply codebuild/samples/linux-smoke-tests.yml:20]: (posting here in case anyone outside if the team is following the PR) - Will continue to look into this and get it working with CI 👍

**Review by bretambrose — COMMENTED** [review]
I think "auth_name" and its variants is kind of confusing.  I would try to give a little bit of hierarchical structure in the names, ala:

```
custom_auth_username
custom_auth_authorizer_name
custom_auth_password
```

etc...

custom_auth_name is just really confusing on first impression

File: samples/CustomAuthorizerConnect/src/main/java/customauthorizerconnect/CustomAuthorizerConnect.java [hunk 6]
```diff
@@ -43,10 +43,10 @@ public static void main(String[] args) {
         cmdUtils.registerProgramName("CustomAuthorizerConnect");
         cmdUtils.addCommonMQTTCommands();
         cmdUtils.registerCommand("client_id", "<int>", "Client id to use (optional, default='test-*').");
-        cmdUtils.registerCommand("auth_username", "<str>", "Username for connecting to custom authorizer (optional, default=null).");
-        cmdUtils.registerCommand("auth_name", "<str>", "Name of custom authorizer (optional, default=null).");
-        cmdUtils.registerCommand("auth_signature", "<str>", "Signature passed when connecting to custom authorizer (optional, default=null).");
-        cmdUtils.registerCommand("auth_password", "<str>", "Password for connecting to custom authorizer (optional, default=null).");
+        cmdUtils.registerCommand("custom_auth_username", "<str>", "Username for connecting to custom authorizer (optional, default=null).");
+        cmdUtils.registerCommand("custom_auth_authorizer_name", "<str>", "Name of custom authorizer (optional, default=null).");
+        cmdUtils.registerCommand("custom_auth_authorier_signature", "<str>", "Signature passed when connecting to custom authorizer (optional, default=null).");
```
Comment (bretambrose) [inline samples/CustomAuthorizerConnect/src/main/java/customauthorizerconnect/CustomAuthorizerConnect.java:48]: authorizer

File: samples/Utils/CommandLineUtils/utils/commandlineutils/CommandLineUtils.java [hunk 7]
```diff
@@ -383,10 +383,10 @@ public void sampleConnectAndDisconnect(MqttClientConnection connection) throws C
     private static final String m_cmd_message = "message";
     private static final String m_cmd_topic = "topic";
     private static final String m_cmd_help = "help";
-    private static final String m_cmd_custom_auth_username = "auth_username";
-    private static final String m_cmd_custom_auth_name = "auth_name";
-    private static final String m_cmd_custom_auth_signature = "auth_signature";
-    private static final String m_cmd_custom_auth_password = "auth_password";
+    private static final String m_cmd_custom_auth_username = "custom_auth_username";
+    private static final String m_cmd_custom_auth_authorizer_name = "custom_auth_authorizer_name";
+    private static final String m_cmd_custom_auth_authorizer_signature = "custom_auth_authorier_signature";
```
Comment (bretambrose) [inline samples/Utils/CommandLineUtils/utils/commandlineutils/CommandLineUtils.java:388]: authorizer

**Review by bretambrose — APPROVED** [review]
(Fix n ship)

**Comment by TwistedTwigleg** [comment]
Thanks for the reviews! Merging into `main`...
